version: "3"
services:
    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www/html
            - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - webserver

    php:
        image: php:7-fpm
        volumes:
            - .:/var/www/html
        depends_on:
            - mariadb
        networks:
            - webserver
            - database

    mariadb:
        image: mariadb:latest
        volumes:
            - .docker/mariadb/init:/docker-entrypoint-initdb.d:z
        ports:
            - "8306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: pokemory
        networks:
            - database

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mariadb
            PMA_USER: admin
            PMA_PASSWORD: admin
        depends_on:
            - mariadb
        networks:
            - database

networks:
    webserver:
        driver: bridge
    database:
        driver: bridge
